# Generated by Django 4.0.10 on 2023-02-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='normalsellerdetails',
            table='normalsellerdetails',
        ),
    ]
