# Generated by Django 4.0.10 on 2023-02-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0002_alter_normalsellerdetails_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericuserdata',
            old_name='bdata',
            new_name='bdate',
        ),
    ]
