# Generated by Django 4.0.10 on 2023-02-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0003_rename_bdata_genericuserdata_bdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericuserdata',
            name='username',
        ),
    ]
