# Generated by Django 4.0.10 on 2023-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0004_remove_genericuserdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuserdata',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
