# Generated by Django 4.0.10 on 2023-02-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0005_genericuserdata_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericuserdata',
            old_name='is_email_verified',
            new_name='is_email_confirmed',
        ),
    ]
