# Generated by Django 4.0.10 on 2023-02-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0007_alter_genericuserdata_id_emailconfirmationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'db_table': 'userban',
                'managed': True,
                'unique_together': {('user_id', 'from_date')},
            },
        ),
    ]
