# Generated by Django 4.0.10 on 2023-02-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0008_userban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalsellerdetails',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='genericuserdatabasic', serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
