# Generated by Django 4.0.10 on 2023-02-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0009_alter_normalsellerdetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalsellerdetails',
            name='userid',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
