# Generated by Django 4.0.10 on 2023-02-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountallusers', '0010_alter_normalsellerdetails_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalsellerdetails',
            old_name='userid',
            new_name='user',
        ),
    ]
